platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/zgpeace/RWPodSpecs.git'

target 'IceCreamShop' do
  pod 'RWPickFlavor', '~> 0.1.0'
  pod 'MBProgressHUD', '~> 1.1.0', :modular_headers => true
end
